In [43]:
import pandas as pd
import numpy as np

In [44]:
df = pd.read_csv("../data/2025/results.csv")

C:\Users\erenb\AppData\Local\Temp\ipykernel_25456\708626990.py:1: DtypeWarning: Columns (0: JobSatPoints_15_TEXT, 1: DatabaseHaveEntry, 2: DevEnvHaveEntry, 3: SOTagsHaveEntry, 4: SOTagsWant Entry, 5: OfficeStackWantEntry, 6: CommPlatformHaveEntr, 7: CommPlatformWantEntr, 8: SO_Actions_15_TEXT, 9: AIAgentOrchestration, 10: AIAgentObsWrite) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/2025/results.csv")

In [45]:
df.shape

(49191, 172)

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), str(119)
memory usage: 64.6 MB

In [47]:
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'ConvertedCompYearly', 'JobSat'],
      dtype='str', length=172)

In [48]:
df.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [49]:
schema_df = pd.read_csv("../data/2025/schema.csv")
schema_df.head()

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0

In [50]:
#pd.set_option('display.max_columns',172)
#pd.set_option('display.max_rows',100)

In [51]:
df.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [52]:
df.tail()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49189,49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49190,49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
# Creating a df
people = {
    "first": ["Corey", "Jane", "John", "Mary"],
    "last": ["Schafer", "Doe", "Doe", "Smith"],
    "email": ["Corey.Schafer@gmail.com", "Jane.Doe@gmail.com", "John.Doe@gmail.com", "Mary.Smith@gmail.com"]
}

print(people["last"])

people_df = pd.DataFrame(people)
people_df

['Schafer', 'Doe', 'Doe', 'Smith']

   first     last                    email
0  Corey  Schafer  Corey.Schafer@gmail.com
1   Jane      Doe       Jane.Doe@gmail.com
2   John      Doe       John.Doe@gmail.com
3   Mary    Smith     Mary.Smith@gmail.com

In [54]:
print(people_df["email"]) ## or df.email; prefer 1st
print(type(people_df["email"]))  ## Columns are Series objects !!!!

0    Corey.Schafer@gmail.com
1         Jane.Doe@gmail.com
2         John.Doe@gmail.com
3       Mary.Smith@gmail.com
Name: email, dtype: str
<class 'pandas.Series'>

In [55]:
people_df[['first', 'last']]
type(people_df[['first', 'last']])  ## DataFrame object !!!

pandas.DataFrame

In [56]:
## Getting a row : loc and iloc

#iloc is used to get rows (and columns) at particular positions in the index (so it only takes integers)
print(people_df.iloc[0])  ## 0th row
print(people_df.iloc[[0, 1]])  ## 0th and 1st rows
print(people_df.iloc[[0, 1],  [0,2]])  ## 0th and 1st rows, 0th and 2nd columns

#loc is used to get rows (and columns) with particular labels from the index. 
# It can also be used with a boolean array and with labels of the columns.
# End is inclusive for loc, but exclusive for iloc
people_df.loc[0]  ## 0th row
people_df.loc[[0, 1], ["first"]]  ## 0th and 1st rows
print(people_df.loc[people_df["last"] == "Doe"])  ## all rows where last name is Doe
people_df.loc[people_df["last"] == "Doe", ["first", "email"]]  ## all rows where last name is Doe, and only first and email columns

first                      Corey
last                     Schafer
email    Corey.Schafer@gmail.com
Name: 0, dtype: str
   first     last                    email
0  Corey  Schafer  Corey.Schafer@gmail.com
1   Jane      Doe       Jane.Doe@gmail.com
   first                    email
0  Corey  Corey.Schafer@gmail.com
1   Jane       Jane.Doe@gmail.com
  first last               email
1  Jane  Doe  Jane.Doe@gmail.com
2  John  Doe  John.Doe@gmail.com

  first               email
1  Jane  Jane.Doe@gmail.com
2  John  John.Doe@gmail.com

In [57]:
## First look at data
df.head()          # first 5 rows
df.head(10)        # first 10 rows
df.tail()          # last 5 rows
df.shape           # rows, columns
df.columns         # column names
df.index           # row index, the range of row indexes
df.info()          # column types + missing values
df.describe()      # numeric summary
df.describe(include="all")  # summary for all column types

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), str(119)
memory usage: 64.6 MB

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
count,49191.000000,49191,49191,48149,48339,44875,42893.000000,46858,33556,45201,...,3760,478,2692,264,8332,859,29194,22540,2.394700e+04,26670.000000
unique,NaN,6,7,8,6,171,NaN,3,2767,5,...,620,332,314,195,1311,421,574,20138,NaN,NaN
top,NaN,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,NaN,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,Ollama,n8n,Grafana + Prometheus,no,ChatGPT;GitHub Copilot,Cursor,When I don’t trust AI’s answers;When I want to...,Problem solving,NaN,NaN
freq,NaN,37467,16519,20278,33750,18613,NaN,32362,632,16403,...,796,28,588,13,669,106,3050,133,NaN,NaN
mean,24596.000000,NaN,NaN,NaN,NaN,NaN,13.367403,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.017615e+05,7.201950
std,14200.362883,NaN,NaN,NaN,NaN,NaN,10.800117,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.617569e+05,1.997245
min,1.000000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+00,0.000000
25%,12298.500000,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.817100e+04,6.000000
50%,24596.000000,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.532000e+04,8.000000
75%,36893.500000,NaN,NaN,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.205960e+05,8.000000
max,49191.000000,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000e+07,10.000000

In [58]:
## Selecting columns
df["Age"] # -> Series object
df[["Age","EdLevel"]] # -> DataFrame object

                   Age                                            EdLevel
0      25-34 years old    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
1      25-34 years old                Associate degree (A.A., A.S., etc.)
2      35-44 years old       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
3      35-44 years old       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
4      35-44 years old    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
...                ...                                                ...
49186  18-24 years old       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
49187  45-54 years old  Some college/university study without earning ...
49188  35-44 years old    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
49189  25-34 years old     Professional degree (JD, MD, Ph.D, Ed.D, etc.)
49190  18-24 years old  Some college/university study without earning ...

[49191 rows x 2 columns]

In [59]:
## Selecting rows with iloc (integer location)
df.iloc[0]            # first row
df.iloc[0:5]          # first 5 rows
df.iloc[0, 1]         # row 0, column 1
df.iloc[0:5, 0:2]     # first 5 rows, first 2 columns

   ResponseId                      MainBranch
0           1  I am a developer by profession
1           2  I am a developer by profession
2           3  I am a developer by profession
3           4  I am a developer by profession
4           5  I am a developer by profession

In [60]:
## Selecting rows and columns with loc (label location) loc[row_indexer, column_indexer]
df.loc[0]                              # row with index label 0
df.loc[:, "EdLevel"]                      # all rows, EdLevel column
df.loc[:, ["EdLevel", "Age"]]             # all rows, selected columns
df.loc[df["WorkExp"] > 25]                 # filtered rows
df.loc[df["WorkExp"] > 25, ["EdLevel", "WorkExp"]] # filtered rows, selected columns

# most important pattern: df.loc[condition, columns]

                                                 EdLevel  WorkExp
20        Professional degree (JD, MD, Ph.D, Ed.D, etc.)     40.0
21     Some college/university study without earning ...     35.0
24     Some college/university study without earning ...     40.0
25          Bachelor’s degree (B.A., B.S., B.Eng., etc.)     37.0
26       Master’s degree (M.A., M.S., M.Eng., MBA, etc.)     26.0
...                                                  ...      ...
49051       Bachelor’s degree (B.A., B.S., B.Eng., etc.)     27.0
49084    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)     46.0
49106       Bachelor’s degree (B.A., B.S., B.Eng., etc.)     29.0
49130     Professional degree (JD, MD, Ph.D, Ed.D, etc.)     33.0
49184     Professional degree (JD, MD, Ph.D, Ed.D, etc.)     30.0

[5623 rows x 2 columns]

In [61]:
## Filtering data
df[df["WorkExp"] > 25]
df[df["MainBranch"] == "I am a developer by profession"]
df[df["MainBranch"].str.contains("developer", case=False, na=False)]
df[(df["WorkExp"] > 25) & (df["MainBranch"] == "I am a developer by profession")]

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
24,25,I am a developer by profession,65 years or older,Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",Transitioning to retirement (gradually reducin...,40.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I’m stuck...,"Real coding skills, assembler, mainframe, COBO...",NaN,9.0
25,26,I am a developer by profession,55-64 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,37.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;GitHub Copilot;Replit,NaN,When I don’t trust AI’s answers;When I want to...,Choosing the best solutions. Converting user r...,108913.0,8.0
26,27,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",None of the above,26.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,The ability to tackle more open ended problems...,162421.0,8.0
32,33,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,26.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,NaN,7.0
40,41,I am a developer by profession,45-54 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,None of the above,33.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to compare different solutions;Oth...,"Actually knowing how code works, knowing how a...",99999.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48937,48938,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc....",29.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,NaN,124738.0,4.0
49044,49045,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,26.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49051,49052,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc....",27.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
49106,49107,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Volunteering (regularly),29.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69008.0,6.0
49130,49131,I am a developer by profession,45-54 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,33.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to fully understand something;When...,"Human interactions, people buy from people.",NaN,8.0

In [62]:
## Sorting values 
df.sort_values("WorkExp")  # Sort by WorkExp ascending
df.sort_values("WorkExp", ascending=False) # Sort by WorkExp descending
df.sort_values(["MainBranch", "WorkExp"], ascending=[True, False]) # Sort by MainBranch ascending, then by WorkExp descending within each MainBranch

df.nlargest(5, "WorkExp")  # Top 5 rows with largest WorkExp
df.nsmallest(5, "WorkExp")  # Top 5 rows with smallest WorkExp

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
17,18,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,NaN,1.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to learn best practices;When I hav...,NaN,NaN,6.0
64,65,I am a developer by profession,18-24 years old,Some college/university study without earning ...,Student,Engaged in paid work (20-29 hours per week),1.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Most,14850.0,7.0
98,99,"I am not primarily a developer, but I write co...",18-24 years old,"Secondary school (e.g. American high school, G...",Student,Attending school (full-time),1.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Writing secure code,NaN,NaN
116,117,I am learning to code,18-24 years old,"Secondary school (e.g. American high school, G...",Student,Attending school (full-time),1.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I have ethical or security concerns about...,"debbugging stuff thats broken, complex math co...",NaN,NaN
118,119,I code primarily as a hobby,18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time);Engaged in paid w...,1.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,"Project planning, software architecture, commu...",48726.0,NaN

In [63]:
# set_index and reset_index

df2=df.set_index("WorkExp")  # set WorkExp column as index, but does not change df itself
#df.set_index("WorkExp", inplace=True)  # set WorkExp column as index, and change df itself
#df.reset_index(inplace=True)  # reset index to default integer index, and change df itself
df2.head()

# useful for grouping, joining, etc.

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
WorkExp,,,,,,,,,,,,,,,,,,,,,
8.0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)","Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2.0,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
10.0,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4.0,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
21.0,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)","No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [64]:
df["ResponseId"]

0            1
1            2
2            3
3            4
4            5
         ...
49186    49187
49187    49188
49188    49189
49189    49190
49190    49191
Name: ResponseId, Length: 49191, dtype: int64

In [65]:
## Missing values
df.isna()              # True/False missing map
print(df.isna().sum())        # missing count per column
df.dropna()            # remove rows with missing values, needs assignment
df.fillna(0)           # replace missing values with 0, needs assignment
print(df["WorkExp"].isna().sum())  # missing count for WorkExp column
df["WorkExp"] = df["WorkExp"].fillna(0)  # replace missing values in WorkExp column with 0, change the column itself (inplace doesnt work for single column)
print(df["WorkExp"].isna().sum())  # missing count for WorkExp column after filling missing values with 0

ResponseId                 0
MainBranch                 0
Age                        0
EdLevel                 1042
Employment               852
                       ...
AIAgentExtWrite        48332
AIHuman                19997
AIOpen                 26651
ConvertedCompYearly    25244
JobSat                 22521
Length: 172, dtype: int64
6298
0

In [66]:
## Adding/modifying columns
df["NewCol"] = 10  # add a new column, all rows will have value 10 in this column
df["NewCol2"] = df["WorkExp"] * 2  # add a new column, values are double of WorkExp column
df["NewCol3"] = df["NewCol"] + df["NewCol2"]  # add a new column, values are sum of NewCol and NewCol2 columns
df["NewCol4"] = np.where(df["WorkExp"] >25, "Experienced", "Less Experienced")  # add a new column, values are "Experienced" if WorkExp > 25, otherwise "Less Experienced"
print(df[["WorkExp", "NewCol", "NewCol2", "NewCol3", "NewCol4"]].head())

   WorkExp  NewCol  NewCol2  NewCol3           NewCol4
0      8.0      10     16.0     26.0  Less Experienced
1      2.0      10      4.0     14.0  Less Experienced
2     10.0      10     20.0     30.0  Less Experienced
3      4.0      10      8.0     18.0  Less Experienced
4     21.0      10     42.0     52.0  Less Experienced

In [67]:
## Dropping columns
df.drop("NewCol", axis=1)  # drop NewCol column, needs assignment
df.drop(columns=["NewCol2", "NewCol3"], inplace=True)  # drop NewCol2 and NewCol3 columns, modify df itself
df = df.drop(columns=["NewCol4"])  # drop NewCol4 column, needs assignment

In [68]:
## Rename columns
df_renamed = df.rename(columns={"WorkExp": "YearsExperience"})  # rename WorkExp column to YearsExperience, change df itself
df_renamed["YearsExperience"]  # or use inplace = True to change df itself
    
# Very useful cleaning pattern
df_renamed.columns = df_renamed.columns.str.replace(" ", "_")  # replace spaces with underscores in column names, change df_renamed itself
df_renamed.columns = df_renamed.columns.str.lower()  # convert column names to lowercase, change df_renamed itself

In [69]:
## Value counts/unique values
print(df["WorkExp"].value_counts())  # count of unique values in WorkExp column
print(df["WorkExp"].nunique())  # number of unique values in WorkExp column
print(df["WorkExp"].unique)  # unique values in WorkExp column
print(np.sort(df["WorkExp"].unique()))  # unique values in WorkExp column, sorted; since unique returns np array

WorkExp
0.0     6298
10.0    2885
3.0     2613
5.0     2563
1.0     2453
        ...
82.0       1
88.0       1
63.0       1
75.0       1
66.0       1
Name: count, Length: 73, dtype: int64
73
<bound method Series.unique of 0         8.0
1         2.0
2        10.0
3         4.0
4        21.0
         ...
49186     0.0
49187    25.0
49188    17.0
49189     2.0
49190     0.0
Name: WorkExp, Length: 49191, dtype: float64>
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.
  56.  57.  58.  59.  60.  61.  63.  65.  66.  68.  69.  70.  75.  82.
  88.  99. 100.]

In [70]:
df[df["WorkExp"] > 25][["EdLevel", "WorkExp"]]  # all rows where WorkExp > 25, and only EdLevel and WorkExp columns

                                                 EdLevel  WorkExp
20        Professional degree (JD, MD, Ph.D, Ed.D, etc.)     40.0
21     Some college/university study without earning ...     35.0
24     Some college/university study without earning ...     40.0
25          Bachelor’s degree (B.A., B.S., B.Eng., etc.)     37.0
26       Master’s degree (M.A., M.S., M.Eng., MBA, etc.)     26.0
...                                                  ...      ...
49051       Bachelor’s degree (B.A., B.S., B.Eng., etc.)     27.0
49084    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)     46.0
49106       Bachelor’s degree (B.A., B.S., B.Eng., etc.)     29.0
49130     Professional degree (JD, MD, Ph.D, Ed.D, etc.)     33.0
49184     Professional degree (JD, MD, Ph.D, Ed.D, etc.)     30.0

[5623 rows x 2 columns]

In [71]:
## apply, map, applymap (deprecated, don't use), replace,  lambda functions
print(people_df)

# apply: apply a function along an axis of the DataFrame (rows or columns)
print(people_df["email"].apply(len)) # apply a function to each element of the Series (column)

def update_email(email):
    return email.upper()
print(people_df["email"].apply(update_email))

# lambda: anonymous function
print(people_df["email"].apply(lambda x: x.lower()))

#applying to df itself
print(people_df.apply(len, axis= "columns")) # return number of columns for each row
print(people_df.apply(pd.Series.min, axis=0))  #default axis=0 # return minimum value for each column

# replace: replace values in a Series or DataFrame
print(people_df["last"].replace({"Doe": "Smith", "Smith": "Johnson"}))  # using map results in NaN for values not in the map

   first     last                    email
0  Corey  Schafer  Corey.Schafer@gmail.com
1   Jane      Doe       Jane.Doe@gmail.com
2   John      Doe       John.Doe@gmail.com
3   Mary    Smith     Mary.Smith@gmail.com
0    23
1    18
2    18
3    20
Name: email, dtype: int64
0    COREY.SCHAFER@GMAIL.COM
1         JANE.DOE@GMAIL.COM
2         JOHN.DOE@GMAIL.COM
3       MARY.SMITH@GMAIL.COM
Name: email, dtype: str
0    corey.schafer@gmail.com
1         jane.doe@gmail.com
2         john.doe@gmail.com
3       mary.smith@gmail.com
Name: email, dtype: str
0    3
1    3
2    3
3    3
dtype: int64
first                      Corey
last                         Doe
email    Corey.Schafer@gmail.com
dtype: str
0    Schafer
1      Smith
2      Smith
3    Johnson
Name: last, dtype: str

In [72]:
## String operations
print(people_df)
print(people_df["first"].str.lower())
print(people_df["first"].str.upper())
print(people_df["first"].str.strip())
print(people_df["first"].str.contains("john", case=False, na=False)) # Check if each value contains "abc" case insensitive, and treat NaN as False
print(people_df["first"].str.replace("John", "newJohn")) # Can use dictionary to replace multiple values, or regex for pattern matching
print(people_df["first"].str.split(" "))

   first     last                    email
0  Corey  Schafer  Corey.Schafer@gmail.com
1   Jane      Doe       Jane.Doe@gmail.com
2   John      Doe       John.Doe@gmail.com
3   Mary    Smith     Mary.Smith@gmail.com
0    corey
1     jane
2     john
3     mary
Name: first, dtype: str
0    COREY
1     JANE
2     JOHN
3     MARY
Name: first, dtype: str
0    Corey
1     Jane
2     John
3     Mary
Name: first, dtype: str
0    False
1    False
2     True
3    False
Name: first, dtype: bool
0      Corey
1       Jane
2    newJohn
3       Mary
Name: first, dtype: str
0    [Corey]
1     [Jane]
2     [John]
3     [Mary]
Name: first, dtype: object

In [73]:
## Adding rows: using loc and concat (append is deprecated, don't use)

# Add one row
people_df.loc[len(people_df)] = ["John", "Doe", "John.Doe@gmail.com"]
print(people_df)

# Add one row with dictionary
people_df.loc[len(people_df)] = {
    "first": "Mary",
    "last": "Smith",
    "email": "Mary.Smith@gmail.com"
}
print(people_df)

# Add multiple rows (concat a DataFrame)
new_rows = pd.DataFrame([
    {"first": "Ali", "last": "Yilmaz", "email": "ali@gmail.com"},
    {"first": "Ayse", "last": "Demir", "email": "ayse@gmail.com"}
])

people_df = pd.concat([people_df, new_rows], ignore_index=True) # always use ignore_index=True to prevent duplicate indexes
print(people_df)

   first     last                    email
0  Corey  Schafer  Corey.Schafer@gmail.com
1   Jane      Doe       Jane.Doe@gmail.com
2   John      Doe       John.Doe@gmail.com
3   Mary    Smith     Mary.Smith@gmail.com
4   John      Doe       John.Doe@gmail.com
   first     last                    email
0  Corey  Schafer  Corey.Schafer@gmail.com
1   Jane      Doe       Jane.Doe@gmail.com
2   John      Doe       John.Doe@gmail.com
3   Mary    Smith     Mary.Smith@gmail.com
4   John      Doe       John.Doe@gmail.com
5   Mary    Smith     Mary.Smith@gmail.com
   first     last                    email
0  Corey  Schafer  Corey.Schafer@gmail.com
1   Jane      Doe       Jane.Doe@gmail.com
2   John      Doe       John.Doe@gmail.com
3   Mary    Smith     Mary.Smith@gmail.com
4   John      Doe       John.Doe@gmail.com
5   Mary    Smith     Mary.Smith@gmail.com
6    Ali   Yilmaz            ali@gmail.com
7   Ayse    Demir           ayse@gmail.com

In [74]:
## Dropping rows: using drop and boolean indexing
print(people_df)

# Drop rows by index
people_df.drop(index=[0, 1], inplace=True)  # drop rows with index
people_df.reset_index(drop=True , inplace=True)  # reset index after dropping rows 
# !!! Important: Index is not automatically reset after dropping rows, so you need to reset it manually if you want a clean index
# Otherwise indexing would start from 2 in this case. 
# drop = True to not to add the old index as a column in the DataFrame
print(people_df)

# Drop rows by condition
people_df = people_df[people_df["last"] != "Doe"]  # drop rows
people_df.reset_index(drop=True , inplace=True)
print(people_df)

# Drop with boolean indexing
people_df.drop(index = people_df[people_df["last"] == "Smith"].index, inplace=True)  # drop rows
people_df.reset_index(drop=True , inplace=True)
print(people_df)

   first     last                    email
0  Corey  Schafer  Corey.Schafer@gmail.com
1   Jane      Doe       Jane.Doe@gmail.com
2   John      Doe       John.Doe@gmail.com
3   Mary    Smith     Mary.Smith@gmail.com
4   John      Doe       John.Doe@gmail.com
5   Mary    Smith     Mary.Smith@gmail.com
6    Ali   Yilmaz            ali@gmail.com
7   Ayse    Demir           ayse@gmail.com
  first    last                 email
0  John     Doe    John.Doe@gmail.com
1  Mary   Smith  Mary.Smith@gmail.com
2  John     Doe    John.Doe@gmail.com
3  Mary   Smith  Mary.Smith@gmail.com
4   Ali  Yilmaz         ali@gmail.com
5  Ayse   Demir        ayse@gmail.com
  first    last                 email
0  Mary   Smith  Mary.Smith@gmail.com
1  Mary   Smith  Mary.Smith@gmail.com
2   Ali  Yilmaz         ali@gmail.com
3  Ayse   Demir        ayse@gmail.com
  first    last           email
0   Ali  Yilmaz   ali@gmail.com
1  Ayse   Demir  ayse@gmail.com

In [75]:
people_df

  first    last           email
0   Ali  Yilmaz   ali@gmail.com
1  Ayse   Demir  ayse@gmail.com

In [ ]:
### Grouping and aggregation
print(df.shape)  # number of rows in the DataFrame
print(df["Employment"].nunique())  # number of unique values in Employment column
print(df["Employment"].count())  #  count of not null values in Employment column
print(df["Employment"].value_counts())  # count of unique values in Employment column
print(df["Employment"].value_counts(normalize=True))  # percentage of unique values in Employment column

print("*"*100)
print(df.groupby("Employment").head().loc[:, ["Employment", "WorkExp"]].sort_values("Employment"))  # first 5 rows of each group, and only Employment and WorkExp columns, sort for better readability
# Means: 
# 1. group by Employment column
# 2. take the first 5 rows of each group
# 3. select only Employment and WorkExp columns for all rows
# 4. sort the result by Employment column for better readability 
# Cleaner way:
print("*"*100, "Cleaner way:")
result = df.groupby("Employment").head(5)
result = result.sort_values("Employment")

print(result.loc[:, ["Employment", "WorkExp"]])

# Aggregation functions: count, mean, median, std, min, max, sum, etc.
print("*"*100, "Aggregation:")
print(df.groupby("Employment")["WorkExp"].mean())  # mean of WorkExp column for each group in Employment column

print("*"*100)
print(df.groupby("Employment")["WorkExp"].agg(["count", "mean", "median", "std"]))  # count, mean, median, std of WorkExp column for each group in Employment column
## Another usage: different operations for different columns and naming those aggregated columns !!
    # print(df.groupby("Employment").agg(
    #     count_column = ("colum1" , "count"), 
    #     avg_column = ("WorkExp", "mean"),
    #     sum_column = ("colum2" , "sum")
    # ))

(49191, 173)
6
48339
Employment
Employed                                                33750
Independent contractor, freelancer, or self-employed     6708
Student                                                  4428
Not employed                                             2227
Retired                                                   708
I prefer not to say                                       518
Name: count, dtype: int64
Employment
Employed                                                0.698194
Independent contractor, freelancer, or self-employed    0.138770
Student                                                 0.091603
Not employed                                            0.046070
Retired                                                 0.014647
I prefer not to say                                     0.010716
Name: proportion, dtype: float64
****************************************************************************************************
                                            Employment  WorkExp
0                                             Employed      8.0
1                                             Employed      2.0
3                                             Employed      4.0
7                                             Employed     22.0
8                                             Employed      9.0
339                                I prefer not to say     10.0
330                                I prefer not to say     20.0
135                                I prefer not to say      2.0
351                                I prefer not to say     15.0
454                                I prefer not to say     14.0
6    Independent contractor, freelancer, or self-em...      9.0
2    Independent contractor, freelancer, or self-em...     10.0
4    Independent contractor, freelancer, or self-em...     21.0
12   Independent contractor, freelancer, or self-em...     10.0
5    Independent contractor, freelancer, or self-em...     15.0
44                                        Not employed      4.0
76                                        Not employed      8.0
124                                       Not employed     12.0
140                                       Not employed     20.0
147                                       Not employed      5.0
16                                             Retired     20.0
56                                             Retired     45.0
78                                             Retired     40.0
112                                            Retired     43.0
175                                            Retired     54.0
15                                             Student      5.0
98                                             Student      1.0
71                                             Student      3.0
86                                             Student      2.0
64                                             Student      1.0
**************************************************************************************************** Cleaner way:
                                            Employment  WorkExp
0                                             Employed      8.0
1                                             Employed      2.0
3                                             Employed      4.0
7                                             Employed     22.0
8                                             Employed      9.0
339                                I prefer not to say     10.0
330                                I prefer not to say     20.0
135                                I prefer not to say      2.0
351                                I prefer not to say     15.0
454                                I prefer not to say     14.0
6    Independent contractor, freelancer, or self-em...      9.0
2    Independent contractor, freelancer, or self-em...     10.0
4    Independent contractor, freelancer, or self-em...     21.0
12   Independent contractor, freelancer, or self-em...     10.0
5    Independent contractor, freelancer, or self-em...     15.0
44                                        Not employed      4.0
76                                        Not employed      8.0
124                                       Not employed     12.0
140                                       Not employed     20.0
147                                       Not employed      5.0
16                                             Retired     20.0
56                                             Retired     45.0
78                                             Retired     40.0
112                                            Retired     43.0
175                                            Retired     54.0
15                                             Student      5.0
98                                             Student      1.0
71                                             Student      3.0
86                                             Student      2.0
64                                             Student      1.0
**************************************************************************************************** Aggregation:

Employment
Employed                                                12.218430
I prefer not to say                                      9.239382
Independent contractor, freelancer, or self-employed    15.879994
Not employed                                             8.383476
Retired                                                 34.546610
Student                                                  1.481030
Name: WorkExp, dtype: float64
****************************************************************************************************
                                                    count       mean  median  \
Employment
Employed                                            33750  12.218430    10.0
I prefer not to say                                   518   9.239382     2.0
Independent contractor, freelancer, or self-emp...   6708  15.879994    14.0
Not employed                                         2227   8.383476     4.0
Retired                                               708  34.546610    39.0
Student                                              4428   1.481030     0.0

                                                          std
Employment
Employed                                             9.767506
I prefer not to say                                 16.386313
Independent contractor, freelancer, or self-emp...  11.998437
Not employed                                        10.940510
Retired                                             16.182196
Student                                              4.897213

In [77]:
# Important patterns:
# 1. Aggregate on a Series
df["WorkExp"].mean()
df["WorkExp"].sum()
df["WorkExp"].min()
df["WorkExp"].max()
df["WorkExp"].count()
df["WorkExp"].agg(["count", "mean", "min", "max"])

# 2. Aggregate on a DataFrame
df.mean(numeric_only=True)
df.sum(numeric_only=True)
df.min()
df.max()
df[["WorkExp", "ConvertedCompYearly", "JobSat"]].agg(["count", "mean", "min", "max"])

# 3. Aggregate after groupby
df.groupby("Employment")["WorkExp"].mean()
df.groupby("Employment")["WorkExp"].agg(["count", "mean", "min", "max"])
df.groupby("Employment")[["WorkExp", "JobSat"]].agg(["count", "mean"])

                                                   WorkExp            JobSat  \
                                                     count       mean  count
Employment
Employed                                             33750  12.218430  21060
I prefer not to say                                    518   9.239382    106
Independent contractor, freelancer, or self-emp...    6708  15.879994   3889
Not employed                                          2227   8.383476    769
Retired                                                708  34.546610     94
Student                                               4428   1.481030    752


                                                        mean
Employment
Employed                                            7.203514
I prefer not to say                                 6.698113
Independent contractor, freelancer, or self-emp...  7.610440
Not employed                                        5.253576
Retired                                             8.063830
Student                                             7.001330

In [78]:
# Example: Find the percentage of people that has experience more than 10 years in each employment group
group = df.groupby("Employment")["WorkExp"]
group_aggregated = group.agg(lambda x: (x >10).mean() * 100)
df_aggregated = group_aggregated.reset_index(name = "percentage")
df_aggregated

# Important: Pandas calls the lambda once per group, not once per row.
# So x is all the WorkExp values for that group, not a single value.
# Therefore x > 10 returns a boolean array for all values in that group.

                                          Employment  percentage
0                                           Employed   46.269630
1                                I prefer not to say   27.606178
2  Independent contractor, freelancer, or self-em...   59.004174
3                                       Not employed   28.019758
4                                            Retired   87.570621
5                                            Student    1.693767

In [79]:
## Merging dataframes (SQL join like operations)
people1 = {
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'], 
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'], 
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', None, np.nan, 'Anonymous@email.com', 'NA'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}

people2 = {
    "first": ["Corey", "Jane", "John", "Mary"],
    "last": ["Schafer", "Doe", "Doe", "Smith"],
    "email": ["Corey.Schafer@gmail.com", "Jane.Doe@gmail.com", "John.Doe@gmail.com", "Mary.Smith@gmail.com"],
    "age": ["33", "55", "63", "28"]
}

df1 = pd.DataFrame(people1)
df2 = pd.DataFrame(people2)

print(df1.head())
print(df2.head())

df_merged1 = pd.merge(df1, df2, on="first")
df_merged2 = pd.merge(df1, df2, on="first", how="inner")
df_merged3 = pd.merge(df1, df2, on="first", how="left")

print(df_merged1.head())
print(df_merged2.head())
print(df_merged3.head())

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
4    NaN      NaN                      NaN  NaN
   first     last                    email age
0  Corey  Schafer  Corey.Schafer@gmail.com  33
1   Jane      Doe       Jane.Doe@gmail.com  55
2   John      Doe       John.Doe@gmail.com  63
3   Mary    Smith     Mary.Smith@gmail.com  28
   first   last_x                  email_x age_x   last_y  \
0  Corey  Schafer  CoreyMSchafer@gmail.com    33  Schafer
1   Jane      Doe        JaneDoe@email.com    55      Doe
2   John      Doe        JohnDoe@email.com    63      Doe

                   email_y age_y
0  Corey.Schafer@gmail.com    33
1       Jane.Doe@gmail.com    55
2       John.Doe@gmail.com    63
   first   last_x                  email_x age_x   last_y  \
0  Corey  Schafer  CoreyMSchafer@gmail.com    33  Schafer
1   Jane      Doe        JaneDoe@email.com    55      Doe
2   John      Doe        JohnDoe@email.com    63      Doe

                   email_y age_y
0  Corey.Schafer@gmail.com    33
1       Jane.Doe@gmail.com    55
2       John.Doe@gmail.com    63
   first   last_x                  email_x age_x   last_y  \
0  Corey  Schafer  CoreyMSchafer@gmail.com    33  Schafer
1   Jane      Doe        JaneDoe@email.com    55      Doe
2   John      Doe        JohnDoe@email.com    63      Doe
3  Chris  Schafer                      NaN    36      NaN
4    NaN      NaN                      NaN   NaN      NaN

                   email_y age_y
0  Corey.Schafer@gmail.com    33
1       Jane.Doe@gmail.com    55
2       John.Doe@gmail.com    63
3                      NaN   NaN
4                      NaN   NaN

In [80]:
# Date Operations

stock_data = {
    "date": [
        "2025-06-01 09-AM",
        "2025-06-01 10-AM",
        "2025-06-01 11-AM",
        "2025-06-01 12-PM",
        "2025-06-01 01-PM",
        "2025-06-01 02-PM",
        "2025-06-01 03-PM",
        "2025-06-01 04-PM",
        "2025-06-01 05-PM",
        "2025-06-01 06-PM"
    ],
    "symbol": [
        "AAPL", "AAPL", "AAPL", "AAPL", "AAPL",
        "MSFT", "MSFT", "MSFT", "MSFT", "MSFT"
    ],
    "open": [
        190.5, 191.2, 192.0, 191.7, 193.1,
        420.0, 421.5, 422.3, 421.8, 423.0
    ],
    "high": [
        192.0, 192.8, 193.5, 193.0, 194.2,
        422.0, 423.1, 424.0, 423.5, 424.8
    ],
    "low": [
        189.8, 190.9, 191.3, 191.0, 192.5,
        419.2, 420.8, 421.4, 420.9, 422.1
    ],
    "close": [
        191.2, 192.0, 191.7, 193.1, 193.8,
        421.5, 422.3, 421.8, 423.0, 424.2
    ],
    "volume": [
        1500000, 1320000, 1750000, 1600000, 1900000,
        1100000, 1250000, 1180000, 1350000, 1420000
    ]
}

stock_df = pd.DataFrame(stock_data)

stock_df.head()

               date symbol   open   high    low  close   volume
0  2025-06-01 09-AM   AAPL  190.5  192.0  189.8  191.2  1500000
1  2025-06-01 10-AM   AAPL  191.2  192.8  190.9  192.0  1320000
2  2025-06-01 11-AM   AAPL  192.0  193.5  191.3  191.7  1750000
3  2025-06-01 12-PM   AAPL  191.7  193.0  191.0  193.1  1600000
4  2025-06-01 01-PM   AAPL  193.1  194.2  192.5  193.8  1900000

In [81]:
# using format strings: 
# %Y: 4-digit year, %m: 2-digit month, %d: 2-digit day, 
# %I: 2-digit hour (12-hour clock),
# %H: 2-digit hour (24-hour clock), %p: AM/PM
stock_df["date"] = pd.to_datetime(stock_df["date"], format="%Y-%m-%d %I-%p")
stock_df["date"]

0   2025-06-01 09:00:00
1   2025-06-01 10:00:00
2   2025-06-01 11:00:00
3   2025-06-01 12:00:00
4   2025-06-01 13:00:00
5   2025-06-01 14:00:00
6   2025-06-01 15:00:00
7   2025-06-01 16:00:00
8   2025-06-01 17:00:00
9   2025-06-01 18:00:00
Name: date, dtype: datetime64[us]

In [82]:
# Getting date components
print(stock_df["date"].dt.year.head())
print(stock_df["date"].dt.month.head())
print(stock_df["date"].dt.day.head())
print(stock_df["date"].dt.day_name().head())

0    2025
1    2025
2    2025
3    2025
4    2025
Name: date, dtype: int32
0    6
1    6
2    6
3    6
4    6
Name: date, dtype: int32
0    1
1    1
2    1
3    1
4    1
Name: date, dtype: int32
0    Sunday
1    Sunday
2    Sunday
3    Sunday
4    Sunday
Name: date, dtype: str

In [83]:
# Dates support min, max, mean, median, std, etc. operations
print(stock_df["date"].min())
print(stock_df["date"].max())
print(stock_df["date"].mean())
print(stock_df["date"].median())
print(stock_df["date"].std())
print(stock_df["date"].describe())

2025-06-01 09:00:00
2025-06-01 18:00:00
2025-06-01 13:30:00
2025-06-01 13:30:00
0 days 03:01:39.541274
count                     10
mean     2025-06-01 13:30:00
min      2025-06-01 09:00:00
25%      2025-06-01 11:15:00
50%      2025-06-01 13:30:00
75%      2025-06-01 15:45:00
max      2025-06-01 18:00:00
Name: date, dtype: object

In [84]:
print(stock_df["date"].dtype)
print(type(stock_df.iloc[0]["date"]))
print(stock_df[stock_df["date"] > "2025-06-01 12:00:00"]["date"])

datetime64[us]
<class 'pandas.Timestamp'>
4   2025-06-01 13:00:00
5   2025-06-01 14:00:00
6   2025-06-01 15:00:00
7   2025-06-01 16:00:00
8   2025-06-01 17:00:00
9   2025-06-01 18:00:00
Name: date, dtype: datetime64[us]

In [85]:
# Exporting data
stock_df.to_csv("../data/stock_data.csv", )  # export to CSV  
stock_df.to_csv("../data/stock_data.csv", sep="\t")  # export to CSV with tab separator
stock_df.to_excel("../data/stock_data.xlsx")  # export to Excel
stock_df.to_json("../data/stock_data.json")  # export to JSON

C:\Users\erenb\AppData\Local\Temp\ipykernel_25456\1484806558.py:5: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  stock_df.to_json("../data/stock_data.json")  # export to JSON

In [86]:
test_df = pd.read_excel("../data/stock_data.xlsx", index_col="date")
test_df.head()

                     Unnamed: 0 symbol   open   high    low  close   volume
date
2025-06-01 09:00:00           0   AAPL  190.5  192.0  189.8  191.2  1500000
2025-06-01 10:00:00           1   AAPL  191.2  192.8  190.9  192.0  1320000
2025-06-01 11:00:00           2   AAPL  192.0  193.5  191.3  191.7  1750000
2025-06-01 12:00:00           3   AAPL  191.7  193.0  191.0  193.1  1600000
2025-06-01 13:00:00           4   AAPL  193.1  194.2  192.5  193.8  1900000